#!/usr/bin/env python3
"""OpenEMS PCB Studio backend.

Serves the editor UI, generates Octave scripts, runs simulations via
Octave/openEMS as a subprocess and reports progress parsed from the
solver output.
"""
import json
import math
import os
import re
import shutil
import signal
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path

from flask import Flask, jsonify, request, send_file, send_from_directory

from gerber import parse_gerber, parse_excellon, GerberError
from scriptgen import generate_script, ValidationError, dump_layers
from touchstone import (parse_touchstone, interpolate, connect, TouchstoneError,
                        _matmul, _solve)
from meshlines import build_mesh, profile_lines, _range_cells

BASE_DIR = Path(__file__).resolve().parent
SIM_ROOT = BASE_DIR / 'sims'
SIM_ROOT.mkdir(exist_ok=True)
PROJ_ROOT = BASE_DIR / 'projects'
PROJ_ROOT.mkdir(exist_ok=True)
DEV_ROOT = BASE_DIR / 'devices'
DEV_ROOT.mkdir(exist_ok=True)


def _safe_device_name(name):
    safe = re.sub(r'[^\w.-]+', '_', (name or '').strip()).strip('._')
    if not re.search(r'\.s\d+p$', safe, re.I):
        return None
    return safe[:80]


def validate_devices(model):
    """Check the project's S-parameter devices; returns enriched device
    list [{ref, pins, file, ts}] or raises ValidationError."""
    devices = model.get('devices') or []
    if not devices:
        return []
    ports = model.get('ports') or []
    port_nums = [int(p['number']) for p in ports]
    if len(set(port_nums)) != len(port_nums):
        raise ValidationError('duplicate port numbers')
    if any(n > 9 for n in port_nums):
        raise ValidationError('S-parameter devices require port numbers 1-9')
    exc = [int(p['number']) for p in ports if p.get('excite')]
    used = set()
    out = []
    for d in devices:
        ref = d.get('ref') or 'device'
        fname = _safe_device_name(d.get('file'))
        path = DEV_ROOT / (fname or '')
        if not fname or not path.is_file():
            raise ValidationError(f'{ref}: touchstone file "{d.get("file")}" not found on server')
        m = re.search(r'\.s(\d+)p$', fname, re.I)
        try:
            ts = parse_touchstone(path.read_text(), int(m.group(1)))
        except TouchstoneError as e:
            raise ValidationError(f'{ref}: bad touchstone file: {e}')
        pins = [int(x) for x in (d.get('pins') or [])]
        if len(pins) != ts['nports'] or len(set(pins)) != len(pins):
            raise ValidationError(
                f'{ref}: needs {ts["nports"]} distinct pin ports (got {pins})')
        for n in pins:
            if n not in port_nums:
                raise ValidationError(f'{ref}: pin port {n} does not exist')
            if n in used:
                raise ValidationError(f'{ref}: port {n} is used by another device')
            if n in exc:
                raise ValidationError(
                    f'{ref}: the excited port {n} cannot be a device pin')
            port = next(p for p in ports if int(p['number']) == n)
            if abs(float(port.get('impedance', 50)) - ts['r']) > ts['r'] * 0.01:
                raise ValidationError(
                    f'{ref}: port {n} impedance {port.get("impedance")} Ω must match '
                    f'the touchstone reference {ts["r"]} Ω')
        used |= set(pins)
        out.append({'ref': ref, 'pins': pins, 'file': fname, 'ts': ts})
    if len(used) >= len(port_nums):
        raise ValidationError('all ports are consumed by devices - none left to measure')
    return out


def _read_column(csv_path):
    """One excitation run's sparams.csv -> (freq list, {port: [complex]})."""
    lines = csv_path.read_text().strip().split('\n')
    header = lines[0].lstrip('#').split(',')
    freq = []
    cols = {}
    labels = []
    for ci in range(1, len(header) - 2, 2):
        num = int(header[ci][1])
        labels.append((ci, num))
        cols[num] = []
    for line in lines[1:]:
        v = [float(x) for x in line.split(',')]
        freq.append(v[0])
        for ci, num in labels:
            cols[num].append(complex(v[ci], v[ci + 1]))
    return freq, cols


def _write_touchstone(path, freq, mats, r=50.0):
    n = len(mats[0])
    out = [f'! generated by OpenEMS PCB Studio ({n}-port)', f'# GHz S RI R {r:g}']
    for k, f in enumerate(freq):
        row = [f'{f / 1e9:.6f}']
        for i in range(n):
            for j in range(n):
                a, b = (j, i) if n == 2 else (i, j)   # 2-port column order
                row.append(f'{mats[k][a][b].real:.6e} {mats[k][a][b].imag:.6e}')
        out.append(' '.join(row))
    path.write_text('\n'.join(out) + '\n')


def combine_devices(run_dir, model, stages, devices):
    """Assemble the full board S-matrix from the excitation runs, fold in
    every device, and rewrite sparams.csv for the external ports."""
    port_nums = sorted(int(p['number']) for p in model['ports'])
    n = len(port_nums)
    idx = {num: i for i, num in enumerate(port_nums)}
    freq = None
    columns = {}
    for st in stages:
        f, cols = _read_column(st['dir'] / 'sparams.csv')
        if freq is None:
            freq = f
        columns[st['exc']] = cols
    board = []
    for k in range(len(freq)):
        m = [[0j] * n for _ in range(n)]
        for jnum, cols in columns.items():
            for inum, vals in cols.items():
                m[idx[inum]][idx[jnum]] = vals[k]
        board.append(m)

    shutil.copy2(run_dir / 'sparams.csv', run_dir / 'sparams_board.csv')
    _write_touchstone(run_dir / f'board_full.s{n}p', freq, board)

    cur_nums = list(port_nums)
    mats = board
    for dev in devices:
        dmats, clamped = interpolate(dev['ts'], freq)
        pin_idx = [cur_nums.index(p) for p in dev['pins']]
        mats = [connect(mats[k], dmats[k], pin_idx) for k in range(len(freq))]
        cur_nums = [x for i, x in enumerate(cur_nums) if i not in pin_idx]

    exc = min(int(p['number']) for p in model['ports'] if p.get('excite'))
    e = cur_nums.index(exc)
    z0 = float(next(p for p in model['ports']
                    if int(p['number']) == exc).get('impedance', 50))
    if len(cur_nums) >= 2:
        _write_touchstone(run_dir / f'combined.s{len(cur_nums)}p', freq, mats)
    # excited-port column plus every port's own reflection S_ii (the full
    # matrix is available, so the GUI can show all external reflections)
    header = '#freq_Hz' + ''.join(f',S{i}{exc}_re,S{i}{exc}_im' for i in cur_nums)
    header += ''.join(f',S{i}{i}_re,S{i}{i}_im' for i in cur_nums if i != exc)
    header += ',Zin_re,Zin_im'
    lines = [header]
    for k, f in enumerate(freq):
        see = mats[k][e][e]
        den = 1 - see
        zin = z0 * (1 + see) / den if abs(den) > 1e-12 else complex(1e9, 0)
        row = [f'{f:e}']
        for i, num in enumerate(cur_nums):
            s = mats[k][i][e]
            row.append(f'{s.real:e},{s.imag:e}')
        for i, num in enumerate(cur_nums):
            if num == exc:
                continue
            s = mats[k][i][i]
            row.append(f'{s.real:e},{s.imag:e}')
        row.append(f'{zin.real:e},{zin.imag:e}')
        lines.append(','.join(row))
    (run_dir / 'sparams.csv').write_text('\n'.join(lines) + '\n')


def merge_excitations(run_dir, model, stages):
    """Merge the per-stage sparams.csv columns of a multi-excitation run
    (a user-selected subset of ports, no devices) into one sparams.csv:
    S_i,e for every excitation e, primary excitation's columns first."""
    freq = None
    parts = []                       # [(exc, {port: [complex]})] primary first
    for st in reversed(stages):      # root (primary) stage is last in stages
        f, cols = _read_column(st['dir'] / 'sparams.csv')
        if freq is None:
            freq = f
        parts.append((st['exc'], cols))
    # Zin of the primary excitation from the root csv (dropped by _read_column)
    root_lines = (run_dir / 'sparams.csv').read_text().strip().split('\n')
    zin = [line.split(',')[-2:] for line in root_lines[1:]]
    shutil.copy2(run_dir / 'sparams.csv', run_dir / 'sparams_primary.csv')
    header = '#freq_Hz'
    for exc, cols in parts:
        header += ''.join(f',S{i}{exc}_re,S{i}{exc}_im' for i in sorted(cols))
    header += ',Zin_re,Zin_im'
    lines = [header]
    for k, f in enumerate(freq):
        row = [f'{f:e}']
        for exc, cols in parts:
            for i in sorted(cols):
                v = cols[i][k]
                row.append(f'{v.real:e},{v.imag:e}')
        row.extend(zin[k])
        lines.append(','.join(row))
    (run_dir / 'sparams.csv').write_text('\n'.join(lines) + '\n')

MAX_LOG_LINES = 5000
# hard ceiling on excitations solved side by side. Each one is a full
# openEMS instance holding its own field arrays, so memory - not cores -
# is what bites first on a large board.
MAX_PARALLEL = 16

# How many cells one openEMS thread can usefully digest: below this the
# per-timestep barrier sync outweighs the extra worker. Measured here: a
# 70k-cell board ran fastest at 1 thread (2 threads were slower than
# sequential), 185k gained only 16% from a second thread, 1.5M peaked at
# 2-4 threads of 8. The rule matters most on many-core servers, where an
# even cores/parallel share alone would hand a medium board 16 threads.
CELLS_PER_THREAD = 150_000


def split_threads(cores, cells, parallel, live, queued):
    """openEMS threads for the next stage launch when several excitations
    share the machine. Left to itself each instance benchmarks thread
    counts at startup - a race: the first calibrates on an idle machine
    and grabs everything, the rest calibrate against that load and settle
    on 1 (a 4-way run was observed splitting 9/1/1/1). So when running
    side by side the split is computed here instead: an even share of the
    cores over the stages actually in flight (a stage launching beside
    fewer live runs gets the correspondingly larger share), capped at
    what the mesh size can put to work."""
    width = max(1, min(parallel, live + queued))
    fair = max(1, cores // width)
    useful = max(1, (cells or 0) // CELLS_PER_THREAD)
    return min(fair, useful)

app = Flask(__name__, static_folder='static', static_url_path='')

TIMESTEP_RE = re.compile(r'Timestep:\s*(\d+)')
ENERGY_RE = re.compile(r'\((-?\s*\d+(?:\.\d+)?)\s*dB\)')
SPEED_RE = re.compile(r'Speed:\s*([\d.]+)\s*MC/s')
WALL_RE = re.compile(r'\[@\s*(\d+)s\]')


class Runner:
    """Manages a single active simulation subprocess."""

    def __init__(self):
        self.lock = threading.Lock()
        self._reset()

    def _reset(self):
        self.run_id = None
        self.state = 'idle'      # idle|starting|running|post|done|error|stopped
        self.percent = 0.0
        self.log = []
        self.mesh_cells = None
        self.error = None
        self.proc = None
        self.started_at = None
        self.nrts = 1
        self.end_db = -40.0
        self.not_converged = False
        self.info = {}           # parsed engine facts (version, dt, ...)
        self.warn_msgs = []      # solver warnings, deduped
        self.stages = []
        # one record per excitation: each Octave run restarts its timestep
        # counter, so samples must not be concatenated. Records exist from
        # the start (state 'queued') so the run view can show the whole
        # plan, not just what has been launched.
        self.stage_data = []
        self.stage_idx = 0
        self.merge_only = False
        self.stage_info = ''
        self.devices = []
        self.base_model = None
        self.project = ''        # which design this run belongs to
        self.parallel = 1        # excitations solved side by side
        self.threads = 0         # openEMS threads per excitation (0 = auto)
        self.auto_split = False  # runner balances threads at each launch
        self.plan_cells = None   # mesh size known before launch
        self.procs = {}          # stage index -> live subprocess

    def _sync_progress_locked(self):
        """Overall progress: the mean over all stages, so every excitation
        contributes its own share whether it runs alone or beside others."""
        n = max(1, len(self.stage_data))
        self.percent = sum(s.get('percent', 0.0) for s in self.stage_data) / n

    def _stage(self):
        """Record of the excitation currently being solved (single-stage
        parsing helper; parallel readers address their record directly)."""
        if not self.stage_data:
            self.stage_data.append(self._new_stage_record(None, 'Run'))
        return self.stage_data[-1]

    @staticmethod
    def _new_stage_record(exc, label):
        return {'exc': exc, 'label': label, 'samples': [], 'info': {},
                'warn': [], 'notConverged': False, 'state': 'queued',
                'percent': 0.0, 'done': False, 'threads': None}

    def status(self, offset=0):
        with self.lock:
            offset = max(0, min(int(offset), len(self.log)))
            # the "current" stage for the single-stage top-level fields:
            # whichever is running (the earliest, when several are), else
            # the last one that produced anything
            cur = None
            for s in self.stage_data:
                if s.get('state') == 'running':
                    cur = s
                    break
            if cur is None and self.stage_data:
                cur = self.stage_data[-1]
            return {
                'runId': self.run_id,
                'state': self.state,
                'percent': round(self.percent, 1),
                'error': self.error,
                'lines': self.log[offset:],
                'nextOffset': len(self.log),
                'elapsed': round(time.time() - self.started_at, 1) if self.started_at else 0,
                # top level mirrors the stage in progress; `stages` carries
                # every excitation separately for the tabbed run view
                'samples': cur['samples'] if cur else [],
                'nrts': self.nrts,
                'endDb': self.end_db,
                'meshCells': self.mesh_cells,
                'notConverged': self.not_converged,
                'info': cur['info'] if cur else {},
                'warnMsgs': cur['warn'] if cur else [],
                'stageInfo': self.stage_info,
                'stageIdx': self.stage_data.index(cur) if cur in self.stage_data else 0,
                'stageCount': max(len(self.stages), len(self.stage_data)),
                'project': self.project,
                'parallel': self.parallel,
                'threads': self.threads,
                'running': sorted(self.procs),
                'stages': [{'exc': s['exc'], 'label': s['label'],
                            'samples': s['samples'], 'info': s['info'],
                            'warn': s['warn'], 'notConverged': s['notConverged'],
                            'state': s.get('state', 'queued'),
                            'percent': round(s.get('percent', 0.0), 1),
                            'threads': s.get('threads')}
                           for s in self.stage_data],
            }

    def start(self, model):
        with self.lock:
            if any(p.poll() is None for p in self.procs.values()):
                raise RuntimeError('A simulation is already running')
            devices = validate_devices(model)   # raises ValidationError
            run_id = time.strftime('run_%Y%m%d_%H%M%S')
            sim_dir = SIM_ROOT / run_id
            # nothing is written until every stage has validated - a
            # rejected run must not leave an empty run directory behind

            # with S-parameter devices (or the full-S-matrix option) one
            # excitation run per port is needed; the user's excited port
            # runs last in the run root. Every stage keeps the configured
            # field dumps, so the current density can be reviewed for each
            # excitation - not only the primary one.
            full_s = bool((model.get('sim') or {}).get('fullS')) \
                and len(model.get('ports') or []) > 1
            excited = sorted(int(p['number']) for p in (model.get('ports') or [])
                             if p.get('excite'))
            if not excited:
                raise ValidationError('No excited port - mark at least one '
                                      'port as the excitation source')

            def stage_model(n):
                m2 = json.loads(json.dumps(model))
                for q in m2['ports']:
                    q['excite'] = (int(q['number']) == n)
                return m2

            # stage list; the primary excitation runs last in the run root
            stages = []
            exc = excited[0]
            if devices or full_s:
                # devices / full S-matrix: one excitation run per port
                sweep = sorted(int(p['number']) for p in model['ports'])
            elif len(excited) > 1:
                # user-selected subset of excitations
                sweep = excited
            else:
                sweep = [exc]
            for n in sweep:
                if n == exc:
                    continue
                stages.append({'dir': sim_dir / f'exc_{n}',
                               'model': stage_model(n), 'exc': n})
            stages.append({'dir': sim_dir, 'model': stage_model(exc),
                           'exc': exc if len(sweep) > 1 else None})
            merge_only = not (devices or full_s) and len(sweep) > 1

            # how many excitations to solve side by side. They are wholly
            # independent runs writing to separate directories, so the only
            # shared resources are cores and memory: the thread budget is
            # split between them, and the user is told the memory multiplies.
            sim_cfg = model.get('sim') or {}
            par = sim_cfg.get('parallel')
            try:
                par = int(par) if par else 1
            except (TypeError, ValueError):
                par = 1
            if par <= 0:                       # 'auto'
                par = max(1, (os.cpu_count() or 1) // 2)
            par = max(1, min(par, len(stages), MAX_PARALLEL))
            # Threads: a SINGLE run is left to openEMS, which benchmarks
            # the actual mesh at startup and picks its own count - that
            # beats anything computed here. Side-by-side runs must NOT be
            # left to it: the startup benchmarks race (the first instance
            # calibrates on an idle machine and grabs every core, the
            # rest calibrate against that load and settle on 1 - observed
            # as a 9/1/1/1 split on a 4-way run), so the runner assigns
            # an even share per launch instead (split_threads). Small
            # meshes get 1 thread each: openEMS gains nothing from more
            # there, and forcing cores/N on the bundled amplifier made a
            # 4-excitation run take 42 s against 17.5 s at 1 thread each.
            # An explicit threadsPerExc overrides all of this.
            threads = sim_cfg.get('threadsPerExc')
            try:
                threads = max(0, int(threads)) if threads else 0
            except (TypeError, ValueError):
                threads = 0

            # validate every stage before anything runs
            for st in stages:
                if threads:
                    st['model'].setdefault('sim', {})['numThreads'] = threads
                st['script'] = generate_script(st['model'])
            # every excitation shares the board geometry, hence the mesh
            plan_cells = build_mesh(model).get('cells')

            self._reset()
            self.run_id = run_id
            self.state = 'starting'
            self.started_at = time.time()
            self.devices = devices
            self.base_model = model
            self.stages = stages
            self.stage_idx = 0
            self.merge_only = merge_only
            self.project = str(model.get('name') or '')
            self.parallel = par
            self.threads = threads
            self.auto_split = threads == 0 and par > 1
            self.plan_cells = plan_cells
            multi = len(stages) > 1
            for i, st in enumerate(stages):
                self.stage_data.append(self._new_stage_record(
                    st.get('exc'),
                    (f'Exc {st["exc"]}' if multi and st.get('exc') is not None
                     else f'Run {i + 1}' if multi else 'Run')))
            # persist the exact model that produced this run: the run stays
            # self-describing and recoverable with no browser involved
            sim_dir.mkdir(parents=True, exist_ok=True)
            (sim_dir / 'project.json').write_text(json.dumps(model, indent=1))
            sim = model.get('sim') or {}
            self.nrts = max(1, int(sim.get('maxTimesteps') or 30000))
            self.end_db = float(sim.get('endCriteria') or -40.0)
            self._pump_locked()
        return run_id

    def _pump_locked(self):
        """Keep `parallel` excitations in flight, launching queued ones as
        slots free up."""
        for idx, rec in enumerate(self.stage_data):
            if len(self.procs) >= self.parallel:
                break
            if rec['state'] != 'queued':
                continue
            try:
                self._launch_stage_locked(idx)
            except Exception as e:
                rec['state'] = 'error'
                self.state = 'error'
                self.error = f'failed to start excitation {idx + 1}: {e}'
                return
        self._update_stage_info_locked()

    def _update_stage_info_locked(self):
        n = len(self.stage_data)
        if n <= 1:
            self.stage_info = ''
            return
        done = sum(1 for s in self.stage_data if s['state'] in ('done', 'error'))
        live = len(self.procs)
        self.stage_info = f'{done}/{n} excitations'
        if live > 1:
            self.stage_info += f' · {live} running in parallel'
            tl = sorted({self.stage_data[i].get('threads') for i in self.procs}
                        - {None})
            if tl:
                self.stage_info += (
                    f' · {tl[0]} thread{"s" if tl[0] != 1 else ""} each'
                    if len(tl) == 1
                    else f' · {"/".join(map(str, tl))} threads')

    def _launch_stage_locked(self, idx):
        st = self.stages[idx]
        rec = self.stage_data[idx]
        st['dir'].mkdir(parents=True, exist_ok=True)
        script = st['script']
        if self.auto_split:
            queued = sum(1 for r in self.stage_data
                         if r['state'] == 'queued')      # includes this one
            t = split_threads(os.cpu_count() or 1, self.plan_cells,
                              self.parallel, len(self.procs), queued)
            # the validated script carries no thread flag; the launch pins
            # this stage's fair share (a lone tail stage gets them all)
            script = script.replace(
                'RunOpenEMS(Sim_Path, Sim_File);',
                f"RunOpenEMS(Sim_Path, Sim_File, '--numThreads={t}');")
            rec['threads'] = t
        (st['dir'] / 'pcb_sim.m').write_text(script)
        rec['state'] = 'running'
        proc = subprocess.Popen(
            ['stdbuf', '-oL', '-eL', 'octave', '--no-gui', '--no-window-system', 'pcb_sim.m'],
            cwd=st['dir'],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        self.procs[idx] = proc
        self.proc = proc          # kept for "is anything running" checks
        threading.Thread(target=self._reader, args=(proc, idx), daemon=True).start()

    def stop(self):
        with self.lock:
            procs = [p for p in self.procs.values() if p.poll() is None]
            if not procs:
                return False
            self.state = 'stopped'
        for proc in procs:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            except (ProcessLookupError, PermissionError):
                pass
        for proc in procs:
            try:
                for _ in range(20):
                    if proc.poll() is not None:
                        break
                    time.sleep(0.25)
                if proc.poll() is None:
                    os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
            except (ProcessLookupError, PermissionError):
                pass
        return True

    # ---- internal ------------------------------------------------------
    def _append_line(self, line, rec=None):
        line = line.rstrip()
        if not line:
            return
        # with several solvers talking at once the shared log needs to say
        # who is speaking, or the interleaving is unreadable
        tag = ''
        if rec is not None and len(self.procs) > 1:
            tag = f'[{rec["label"]}] '
        self.log.append(tag + line)
        if len(self.log) > MAX_LOG_LINES:
            del self.log[:len(self.log) - MAX_LOG_LINES]
        self._parse(line, rec)

    INFO_PATTERNS = [
        ('version', re.compile(r'openEMS \d+bit -- version (\S+)')),
        ('engine', re.compile(r'Create FDTD operator \((.+)\)')),
        ('threads', re.compile(r'Best performance found using (\d+) threads')),
        ('fdtdSize', re.compile(r'FDTD simulation size:\s*(\d+x\d+x\d+)')),
        ('dt', re.compile(r'FDTD timestep is:\s*([0-9.eE+-]+)\s*s')),
        ('nyquist', re.compile(r'Nyquist rate:\s*(\d+)\s*timesteps')),
        ('excitationTs', re.compile(r'Excitation signal length is:\s*(\d+)\s*timesteps')),
        ('excitationS', re.compile(r'Excitation signal length is:.*\(([0-9.eE+-]+)s\)')),
        ('maxTs', re.compile(r'Max. number of timesteps:\s*(\d+)')),
        ('finalSpeed', re.compile(r'^Speed:\s*([\d.]+)\s*MCells/s')),
        ('runTime', re.compile(r'Time for \d+ iterations with [\d.]+ cells\s*:\s*([\d.]+)\s*sec')),
    ]

    def _parse(self, line, stage=None):
        if stage is None:
            stage = self._stage()
        stage.setdefault('state', 'running')
        stage.setdefault('percent', 0.0)
        stage.setdefault('done', False)
        self.info = stage['info']
        self.warn_msgs = stage['warn']
        for key, rx in self.INFO_PATTERNS:
            m = rx.search(line)
            if m:
                self.info[key] = m.group(1)
        low = line.lower()
        if 'warning' in low and 'gui_marker' not in low:
            msg = line.strip()
            if msg not in self.warn_msgs and len(self.warn_msgs) < 20:
                self.warn_msgs.append(msg)
        elif self.warn_msgs and line.startswith('\t'):
            # openEMS continues warnings on indented lines
            if len(self.warn_msgs[-1]) < 400:
                self.warn_msgs[-1] += ' ' + line.strip()
        if 'GUI_MARKER: starting FDTD' in line:
            stage['state'] = 'running'
            if self.state == 'starting':
                self.state = 'running'
        elif 'GUI_MARKER: mesh' in line:
            m = re.search(r'=\s*(\d+)\s*cells', line)
            if m:
                self.mesh_cells = int(m.group(1))
        elif 'Max. number of timesteps was reached before the end-criteria' in line:
            self.not_converged = True
            stage['notConverged'] = True
        elif 'GUI_MARKER: post-processing' in line:
            stage['state'] = 'post'
            stage['percent'] = max(stage['percent'], 97.0)
            self._sync_progress_locked()
        elif 'GUI_MARKER: done' in line:
            stage['done'] = True
            stage['percent'] = max(stage['percent'], 99.9)
            self._sync_progress_locked()
        elif stage['state'] in ('queued', 'running'):
            pct = None
            sample = {}
            m = TIMESTEP_RE.search(line)
            if m:
                self.state = 'running'
                sample['ts'] = int(m.group(1))
                pct = 100.0 * sample['ts'] / self.nrts
            m = ENERGY_RE.search(line)
            if m and self.end_db < 0:
                db = float(m.group(1).replace(' ', ''))
                sample['db'] = db
                if db < 0:
                    pct = max(pct or 0.0, 100.0 * db / self.end_db)
            if 'ts' in sample:
                m = SPEED_RE.search(line)
                if m:
                    sample['speed'] = float(m.group(1))
                m = WALL_RE.search(line)
                if m:
                    sample['t'] = int(m.group(1))
                stage['samples'].append(sample)
                if len(stage['samples']) > 2000:
                    del stage['samples'][:1000]
            if pct is not None:
                stage['percent'] = max(stage['percent'], min(96.0, pct))
                self._sync_progress_locked()

    def _reader(self, proc, idx=0):
        buf = b''
        stream = proc.stdout
        rec = self.stage_data[idx] if idx < len(self.stage_data) else None
        while True:
            chunk = stream.read(256)
            if not chunk:
                break
            buf += chunk
            # openEMS updates the timestep line with \r; treat it as a newline
            parts = re.split(rb'[\r\n]', buf)
            buf = parts.pop()
            with self.lock:
                for p in parts:
                    self._append_line(p.decode('utf-8', 'replace'), rec)
        rc = proc.wait()
        with self.lock:
            if buf:
                self._append_line(buf.decode('utf-8', 'replace'), rec)
            self.procs.pop(idx, None)
            if self.state == 'stopped':
                if rec is not None:
                    rec['state'] = 'stopped'
                return
            stage_ok = rc == 0 and rec is not None and rec['done']
            if not stage_ok:
                # the first failure owns the error; the siblings it takes
                # down with it were cancelled, not broken
                if rec is not None:
                    rec['state'] = 'error' if self.state != 'error' else 'cancelled'
                if self.state != 'error':
                    self.state = 'error'
                    label = rec['label'] if rec else 'the run'
                    self.error = f'{label}: Octave exited with code {rc}'
                    tail = [l for l in self.log[-15:] if 'error' in l.lower()]
                    if tail:
                        self.error += ': ' + tail[-1]
                    self._write_diagnostics_locked()
                # a failed excitation makes the combination meaningless -
                # stop the others rather than burn cores on a dead run
                siblings = [p for p in self.procs.values() if p.poll() is None]
                threading.Thread(target=self._kill_all, args=(siblings,),
                                 daemon=True).start()
                return
            rec['state'] = 'done'
            rec['percent'] = 100.0
            self._sync_progress_locked()
            if any(s['state'] == 'queued' for s in self.stage_data):
                self._pump_locked()
                return
            if self.procs:
                self._update_stage_info_locked()
                return              # siblings still solving
            # every stage finished
            self.state = 'post'
            self.stage_info = 'combining excitations'
            if len(self.stages) > 1:
                try:
                    if self.merge_only:
                        merge_excitations(SIM_ROOT / self.run_id,
                                          self.base_model, self.stages)
                        self._append_line('GUI_MARKER: excitation columns merged')
                    else:
                        combine_devices(SIM_ROOT / self.run_id, self.base_model,
                                        self.stages, self.devices)
                        self._append_line('GUI_MARKER: full S-matrix assembled'
                                          + (' and device networks folded' if self.devices else ''))
                except Exception as e:
                    self.state = 'error'
                    self.error = f'combining the excitation runs failed: {e}'
                    self._write_diagnostics_locked()
                    return
            self.percent = 100.0
            self.state = 'done'
            self.stage_info = ''
            self._write_diagnostics_locked()
            self._autosave_locked()

    @staticmethod
    def _kill_all(procs):
        for proc in procs:
            try:
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
            except (ProcessLookupError, PermissionError):
                pass

    def _write_diagnostics_locked(self):
        """Persist the Run-tab diagnostics next to the results: the
        per-excitation energy/speed sample series, engine facts and
        solver warnings. The file rides along when the run is attached
        to its project, so the plots and the stats table can be reviewed
        for any past run."""
        try:
            now = time.time()
            d = {'runId': self.run_id, 'state': self.state,
                 'startedAt': self.started_at, 'finishedAt': now,
                 'elapsed': round(now - (self.started_at or now), 1),
                 'meshCells': self.mesh_cells, 'nrts': self.nrts,
                 'endDb': self.end_db, 'error': self.error,
                 'stages': self.stage_data}
            (SIM_ROOT / self.run_id / 'diagnostics.json').write_text(json.dumps(d))
        except Exception as e:
            self.log.append(f'GUI_MARKER: saving run diagnostics failed: {e}')

    def _autosave_locked(self):
        """Attach the finished run's results to its project on disk right
        away, so nothing depends on a browser being open when the
        simulation ends. The project design itself is only written if the
        project does not exist yet (a later manual Save wins otherwise);
        the run directory keeps the authoritative model in project.json."""
        name = _safe_project_name((self.base_model or {}).get('name'))
        if not name:
            return   # unnamed project: recoverable via the run browser
        try:
            pdir = PROJ_ROOT / name
            pdir.mkdir(parents=True, exist_ok=True)
            pj = pdir / 'project.json'
            if not pj.is_file():
                pj.write_text(json.dumps(self.base_model, indent=1))
            # one directory per run: results + the design that produced them
            # (the run dir's project.json rides along in the copy)
            _copy_results(SIM_ROOT / self.run_id, pdir / 'runs' / self.run_id)
            self.log.append(f'GUI_MARKER: results saved to project "{name}"')
        except Exception as e:
            self.log.append(f'GUI_MARKER: attaching results to the project failed: {e}')


runner = Runner()


class TestRunner:
    """Runs the verification suite (unit tier via pytest, benchmark cases
    via scriptgen + octave) in a background thread and reports structured
    reference-vs-obtained metrics."""

    def __init__(self):
        self.lock = threading.Lock()
        self._reset()

    def _reset(self):
        self.state = 'idle'      # idle|running|done
        self.current = None
        self.unit = None         # {status, passed, failed, detail}
        self.results = {}        # case_id -> {status, metrics, elapsed, error}
        self.queue = []
        self.started_at = None

    def status(self):
        with self.lock:
            return {
                'state': self.state,
                'current': self.current,
                'unit': self.unit,
                'results': self.results,
                'queue': self.queue,
                'elapsed': round(time.time() - self.started_at, 1) if self.started_at else 0,
            }

    def start(self, run_unit, case_ids):
        with self.lock:
            if self.state == 'running':
                raise RuntimeError('tests are already running')
            if runner.state in ('starting', 'running', 'post'):
                raise RuntimeError('a simulation is running - wait for it to finish')
            self._reset()
            self.state = 'running'
            self.started_at = time.time()
            self.queue = list(case_ids)
            if run_unit:
                self.unit = {'status': 'running'}
            for cid in case_ids:
                self.results[cid] = {'status': 'queued'}
        threading.Thread(target=self._worker, args=(run_unit, case_ids), daemon=True).start()

    def _worker(self, run_unit, case_ids):
        if run_unit:
            self._run_unit()
        sys.path.insert(0, str(BASE_DIR / 'tests'))
        try:
            from cases import CASES
            from helpers import run_sim
        except Exception as e:
            with self.lock:
                for cid in case_ids:
                    self.results[cid] = {'status': 'error', 'error': f'cannot load cases: {e}'}
                self.state = 'done'
                self.current = None
            return
        for cid in case_ids:
            case = CASES.get(cid)
            if case is None:
                with self.lock:
                    self.results[cid] = {'status': 'error', 'error': 'unknown case'}
                continue
            with self.lock:
                self.current = cid
                self.results[cid] = {'status': 'running'}
            t0 = time.time()
            try:
                rows = run_sim(case['build'](), f'gui_{cid}', timeout=600)
                metrics = case['evaluate'](rows)
                ok = all(m['pass'] for m in metrics)
                with self.lock:
                    self.results[cid] = {
                        'status': 'pass' if ok else 'fail',
                        'metrics': metrics,
                        'elapsed': round(time.time() - t0, 1),
                    }
            except Exception as e:
                with self.lock:
                    self.results[cid] = {
                        'status': 'error',
                        'error': str(e)[-600:],
                        'elapsed': round(time.time() - t0, 1),
                    }
        with self.lock:
            self.state = 'done'
            self.current = None

    def _run_unit(self):
        try:
            res = subprocess.run(
                [sys.executable or 'python3', '-m', 'pytest', '-m', 'not sim', '--tb=line'],
                cwd=BASE_DIR, capture_output=True, text=True, timeout=180)
            out = res.stdout + res.stderr
            m = re.search(r'(\d+) passed', out)
            f = re.search(r'(\d+) failed', out)
            with self.lock:
                self.unit = {
                    'status': 'pass' if res.returncode == 0 else 'fail',
                    'passed': int(m.group(1)) if m else 0,
                    'failed': int(f.group(1)) if f else 0,
                    'detail': out[-1500:] if res.returncode != 0 else '',
                }
        except Exception as e:
            with self.lock:
                self.unit = {'status': 'error', 'detail': str(e)}


test_runner = TestRunner()


@app.get('/')
def index():
    return send_from_directory(app.static_folder, 'index.html')


@app.post('/api/script')
def api_script():
    model = request.get_json(force=True)
    # a script can only excite one port - keep the primary (lowest-numbered)
    excited = sorted(int(p['number']) for p in (model.get('ports') or [])
                     if p.get('excite'))
    note = None
    if len(excited) > 1:
        for p in model['ports']:
            p['excite'] = (int(p['number']) == excited[0])
        note = (f'{len(excited)} ports are marked excited - the exported '
                f'script excites port {excited[0]} only')
    try:
        script = generate_script(model)
    except ValidationError as e:
        return jsonify({'error': str(e)}), 400
    return jsonify({'script': script, 'note': note})


@app.post('/api/run')
def api_run():
    try:
        run_id = runner.start(request.get_json(force=True))
    except ValidationError as e:
        return jsonify({'error': str(e)}), 400
    except RuntimeError as e:
        return jsonify({'error': str(e)}), 409
    return jsonify({'runId': run_id})


@app.get('/api/status')
def api_status():
    return jsonify(runner.status(request.args.get('offset', 0)))


@app.post('/api/stop')
def api_stop():
    return jsonify({'stopped': runner.stop()})


@app.post('/api/mesh')
def api_mesh():
    try:
        mesh = build_mesh(request.get_json(force=True))
    except (ValidationError, KeyError, TypeError, ValueError) as e:
        return jsonify({'error': str(e)}), 400
    return jsonify(mesh)


@app.post('/api/mesh/profile')
def api_mesh_profile():
    """Lines one manual range would produce - the density-profile editor
    previews from the same code that meshes, so what is drawn is what is
    simulated."""
    p = request.get_json(force=True) or {}
    try:
        lo, hi = float(p.get('from') or 0.0), float(p.get('to') or 0.0)
        lo, hi = min(lo, hi), max(lo, hi)
        off = max(0.0, float(p.get('offset') or 0.0))
        # the line-free edge bands are mesh cells too: previewing them
        # keeps the reported smallest/largest cell honest
        off = min(off, (hi - lo) / 2.0 - 1e-6) if off > 0 else 0.0
        inner = (lo + off, hi - off) if off > 0 else (lo, hi)
        # the count may be given directly or as a target spacing - the
        # preview resolves it exactly as the mesher does
        cells = _range_cells(p, inner[1] - inner[0])
        lines = profile_lines(inner[0], inner[1], cells,
                              float(p.get('ratio') or 1.0),
                              str(p.get('bias') or 'uniform'))
    except (TypeError, ValueError) as e:
        return jsonify({'error': str(e)}), 400
    if off > 0 and lines:
        lines = [lo] + lines + [hi]
    widths = [b - a for a, b in zip(lines, lines[1:])]
    return jsonify({'lines': lines, 'band': off or None, 'cells': cells,
                    'minCell': round(min(widths), 6) if widths else None,
                    'maxCell': round(max(widths), 6) if widths else None})


def _safe_project_name(name):
    safe = re.sub(r'[^\w.-]+', '_', (name or '').strip()).strip('._')
    return safe[:60] or None


def _run_dir(run_id):
    """Resolve a results id: run_* under sims/, proj_<name>__run_* for a
    stored project run, and legacy proj_<name> for the old single copy."""
    if re.fullmatch(r'run_[0-9_]+', run_id):
        d = SIM_ROOT / run_id
        return d if d.is_dir() else None
    m = re.fullmatch(r'proj_([\w.-]+)__(run_[0-9_]+)', run_id)
    if m:
        d = PROJ_ROOT / m.group(1) / 'runs' / m.group(2)
        return d if d.is_dir() else None
    m = re.fullmatch(r'proj_([\w.-]+)', run_id)
    if m:
        d = PROJ_ROOT / m.group(1) / 'results'
        return d if d.is_dir() else None
    return None


def _project_runs(safe):
    """Stored runs of a project, newest first: [{runId, mtime, hasResults,
    stages, hasDesign, resultsId}], including the legacy single copy."""
    out = []
    pdir = PROJ_ROOT / safe
    for d in sorted((pdir / 'runs').glob('run_*'), reverse=True):
        if not d.is_dir():
            continue
        out.append({
            'runId': d.name,
            'mtime': d.stat().st_mtime,
            'hasResults': (d / 'sparams.csv').is_file(),
            'stages': 1 + sum(1 for _ in d.glob('exc_*/sparams.csv')),
            'hasDesign': (d / 'project.json').is_file(),
            'resultsId': f'proj_{safe}__{d.name}',
        })
    legacy = pdir / 'results'
    if (legacy / 'sparams.csv').is_file():
        out.append({
            'runId': None,
            'mtime': legacy.stat().st_mtime,
            'hasResults': True,
            'stages': 1 + sum(1 for _ in legacy.glob('exc_*/sparams.csv')),
            'hasDesign': (legacy / 'project.json').is_file(),
            'resultsId': f'proj_{safe}',
        })
    return out


def _read_probe(path):
    """openEMS probe file: comment lines then two whitespace-separated
    columns (time, value)."""
    t, v = [], []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith(('%', '#')):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            try:
                t.append(float(parts[0]))
                v.append(float(parts[1]))
            except ValueError:
                continue
    return t, v


@app.get('/api/results/<run_id>/timedomain')
def api_timedomain(run_id):
    """Port voltage/current signals u(t), i(t) recorded by the ports -
    the full run duration, decimated to a plottable size. ?exc=<port>
    serves the signals of that excitation stage instead of the final
    one; the root response lists the stages that carry their own."""
    sim_dir = _dump_dir(run_id)
    if sim_dir is None:
        return jsonify({'error': 'bad run id'}), 400
    # lumped ports write port_ut{N}; MSL ports write port_ut{N}A/B/C probes
    # around the measurement plane (B sits on it) and port_it{N}A/B either
    # side of it (calcPort averages them)
    variants = {}
    for ut in sim_dir.glob('port_ut*'):
        m = re.fullmatch(r'port_ut_?(\d+)([ABC])?', ut.name)
        if m:
            variants.setdefault(int(m.group(1)), {})[m.group(2) or ''] = ut
    ports = []
    for n in sorted(variants):
        v = variants[n]
        ut = v.get('') or v.get('B') or v.get('A')
        if ut is None:
            continue
        t, u = _read_probe(ut)
        i_vals = []
        if '' in v:   # lumped port
            for it_name in (f'port_it_{n}', f'port_it{n}'):
                it_path = sim_dir / it_name
                if it_path.is_file():
                    i_vals = _read_probe(it_path)[1]
                    break
        else:         # MSL port: average the probes straddling the plane

            acc = []
            for sfx in ('A', 'B'):
                it_path = sim_dir / f'port_it{n}{sfx}'
                if it_path.is_file():
                    acc.append(_read_probe(it_path)[1])
            if acc:
                nmin = min(len(a) for a in acc)
                i_vals = [sum(a[k] for a in acc) / len(acc) for k in range(nmin)]
        ports.append({'n': n, 't': t, 'u': u, 'i': i_vals})
    if not ports:
        return jsonify({'error': 'no time-domain data for this run'}), 404
    # decimate to a plottable size on a common stride
    nmax = max(len(p['t']) for p in ports)
    stride = max(1, nmax // 4000)
    out = []
    for p in ports:
        out.append({
            'n': p['n'],
            't': p['t'][::stride],
            'u': p['u'][::stride],
            'i': p['i'][::stride],
        })
    excs = []
    if not request.args.get('exc'):
        excs = sorted(int(p.name[4:]) for p in sim_dir.glob('exc_*')
                      if p.name[4:].isdigit() and any(p.glob('port_ut*')))
    return jsonify({'ports': out, 'excs': excs})


@app.get('/api/results/<run_id>/sparams.csv')
def api_results(run_id):
    d = _run_dir(run_id)
    if d is None or not (d / 'sparams.csv').is_file():
        return jsonify({'error': 'no results for this run'}), 404
    return send_from_directory(d, 'sparams.csv')


def _dump_dir(run_id):
    """Directory holding the requested current-density dumps: the run
    root, or an excitation stage subdir when ?exc=<port> is given."""
    d = _run_dir(run_id)
    if d is None:
        return None
    exc = request.args.get('exc') or ''
    if exc:
        if not re.fullmatch(r'\d{1,3}', exc):
            return None
        d = d / f'exc_{exc}'
        if not d.is_dir():
            return None
    return d


@app.get('/api/results/<run_id>/jdumps')
def api_jdumps(run_id):
    d = _dump_dir(run_id)
    if d is None:
        return jsonify({'dumps': [], 'excs': []})
    dumps = []
    if (d / 'jdumps.csv').is_file():
        for line in (d / 'jdumps.csv').read_text().strip().splitlines():
            parts = line.split(',')
            if len(parts) == 3 and (d / f'J_{re.sub(r"[^A-Za-z0-9]", "_", parts[0])}_f{parts[1]}.bin').is_file():
                dumps.append({'layer': parts[0], 'k': int(parts[1]), 'freq': float(parts[2])})
    # which other excitations of this run carry their own dumps, and
    # whether the folded steady-state view is available (devices + full
    # board matrix + a frequency dump in every stage)
    excs = []
    steady = False
    if not request.args.get('exc'):
        excs = sorted(int(p.name[4:]) for p in d.glob('exc_*')
                      if p.name[4:].isdigit()
                      and ((p / 'jdumps.csv').is_file() or (p / 'jtdumps.csv').is_file()))
        ctx, _err = _steady_context(d)
        if ctx is not None:
            _model, port_nums, primary, _devices, _ts = ctx
            steady = bool(dumps) and all(
                (_stage_dump_dir(d, n, primary) / 'jdumps.csv').is_file()
                for n in port_nums)
    return jsonify({'dumps': dumps, 'excs': excs, 'steady': steady})


@app.get('/api/results/<run_id>/jdump/<layer>/<int:k>')
def api_jdump(run_id, layer, k):
    d = _dump_dir(run_id)
    fname = f'J_{re.sub(r"[^A-Za-z0-9]", "_", layer)}_f{k}.bin'
    if d is None or not (d / fname).is_file():
        return jsonify({'error': 'no such dump'}), 404
    return send_from_directory(d, fname, mimetype='application/octet-stream')


def _stage_dump_dir(root, port_num, primary):
    return root if port_num == primary else root / f'exc_{port_num}'


def _steady_context(root):
    """(port_nums, primary, devices, board_ts) of a run whose stages can
    be superposed into the folded steady state, or (None, reason)."""
    pj = root / 'project.json'
    if not pj.is_file():
        return None, 'run has no stored model'
    model = json.loads(pj.read_text())
    devices = model.get('devices') or []
    if not devices:
        return None, 'steady state needs S-parameter devices'
    port_nums = sorted(int(p['number']) for p in model.get('ports') or [])
    excited = [int(p['number']) for p in model['ports'] if p.get('excite')]
    primary = min(excited) if excited else port_nums[0]
    board = next(iter(root.glob('board_full.s*p')), None)
    if board is None:
        return None, 'run has no full board S-matrix'
    m = re.fullmatch(r'board_full\.s(\d+)p', board.name)
    ts = parse_touchstone(board.read_text(), int(m.group(1)))
    return (model, port_nums, primary, devices, ts), None


@app.get('/api/results/<run_id>/jsteady/<layer>/<int:k>')
def api_jsteady(run_id, layer, k):
    """Steady-state current density of the COMBINED network (device
    networks folded in) at dump frequency k: the complex superposition
    of every excitation stage's field, weighted by the incident waves
    the devices impose. ?drive=<port> picks the driven external port
    (default: the primary excitation)."""
    root = _run_dir(run_id)
    if root is None:
        return jsonify({'error': 'bad run id'}), 400
    ctx, err = _steady_context(root)
    if ctx is None:
        return jsonify({'error': err}), 404
    model, port_nums, primary, devices, board_ts = ctx

    # dump frequency for k (all stages share the dump list)
    freq = None
    jd = root / 'jdumps.csv'
    if jd.is_file():
        for line in jd.read_text().strip().splitlines():
            parts = line.split(',')
            if len(parts) == 3 and parts[0] == layer and int(parts[1]) == k:
                freq = float(parts[2])
    if freq is None:
        return jsonify({'error': 'no such dump'}), 404

    # incident-wave vector: unit wave into the driven external port, the
    # device pins reflect/transmit the board's outgoing waves
    drive = request.args.get('drive')
    drive = int(drive) if drive and drive.isdigit() else primary
    pins_all = [p for dev in devices for p in dev['pins']]
    if drive in pins_all or drive not in port_nums:
        return jsonify({'error': f'port {drive} is not an external port'}), 400
    idx = {num: i for i, num in enumerate(port_nums)}
    board = interpolate(board_ts, [freq])[0][0]
    kk = len(pins_all)
    sd = [[0j] * kk for _ in range(kk)]
    off = 0
    for dev in devices:
        f = DEV_ROOT / dev['file']
        m = re.search(r'\.s(\d+)p$', dev['file'], re.I)
        if not f.is_file() or not m:
            return jsonify({'error': f'device file {dev["file"]} missing'}), 404
        dts = parse_touchstone(f.read_text(), int(m.group(1)))
        dmat = interpolate(dts, [freq])[0][0]
        for i in range(len(dmat)):
            for j in range(len(dmat)):
                sd[off + i][off + j] = dmat[i][j]
        off += len(dmat)
    pin_idx = [idx[p] for p in pins_all]
    ext_idx = [i for i in range(len(port_nums)) if i not in pin_idx]
    a_e = {i: (1.0 + 0j) if port_nums[i] == drive else 0j for i in ext_idx}
    sce = [[board[pin_idx[i]][j] for j in ext_idx] for i in range(kk)]
    scc = [[board[pin_idx[i]][pin_idx[j]] for j in range(kk)] for i in range(kk)]
    sdscc = _matmul(sd, scc)
    i_minus = [[(1 if i == j else 0) - sdscc[i][j] for j in range(kk)]
               for i in range(kk)]
    rhs = _matmul(sd, [[sum(sce[i][c] * a_e[ext_idx[c]] for c in range(len(ext_idx)))]
                       for i in range(kk)])
    a_c = _solve(i_minus, rhs)
    a = [0j] * len(port_nums)
    for i in ext_idx:
        a[i] = a_e[i]
    for i in range(kk):
        a[pin_idx[i]] = a_c[i][0]

    # superpose the per-stage complex dumps (identical grids by
    # construction: same run, same mesh)
    fname = f'J_{re.sub(r"[^A-Za-z0-9]", "_", layer)}_f{k}.bin'
    import struct
    out_head = None
    out_coords = None
    acc = None
    for num in port_nums:
        sdir = _stage_dump_dir(root, num, primary)
        fpath = sdir / fname
        if not fpath.is_file():
            return jsonify({'error': f'excitation {num} has no dump for this '
                            'frequency - re-run with field dumps enabled'}), 404
        raw = fpath.read_bytes()
        n1, n2 = struct.unpack_from('<2i', raw, 0)
        ncoord = n1 + n2
        nfield = n1 * n2
        vals = struct.unpack_from(f'<{ncoord + 4 * nfield}f', raw, 8)
        head, coords = raw[:8], vals[:ncoord]
        fields = vals[ncoord:]
        if acc is None:
            out_head, out_coords = head, coords
            acc = [0.0] * (4 * nfield)
        elif head != out_head:
            return jsonify({'error': 'stage dumps have mismatched grids'}), 500
        w = a[idx[num]]
        for comp in range(2):                     # jx then jy
            re_off = (2 * comp) * nfield
            im_off = (2 * comp + 1) * nfield
            for i in range(nfield):
                jr = fields[re_off + i]
                ji = fields[im_off + i]
                acc[re_off + i] += w.real * jr - w.imag * ji
                acc[im_off + i] += w.real * ji + w.imag * jr
    blob = out_head + struct.pack(f'<{len(out_coords)}f', *out_coords) \
        + struct.pack(f'<{len(acc)}f', *acc)
    return app.response_class(blob, mimetype='application/octet-stream')


@app.get('/api/results/<run_id>/diagnostics')
def api_run_diagnostics(run_id):
    """Saved Run-tab diagnostics of a completed run (energy/speed sample
    series per excitation, engine facts, warnings)."""
    d = _run_dir(run_id)
    if d is None or not (d / 'diagnostics.json').is_file():
        return jsonify({'error': 'no diagnostics stored for this run'}), 404
    return send_from_directory(d, 'diagnostics.json', mimetype='application/json')


@app.get('/api/devices')
def api_devices_list():
    out = []
    for f in sorted(DEV_ROOT.iterdir()):
        m = re.search(r'\.s(\d+)p$', f.name, re.I)
        if not m:
            continue
        try:
            ts = parse_touchstone(f.read_text(), int(m.group(1)))
            out.append({'file': f.name, 'nports': ts['nports'], 'r': ts['r'],
                        'fmin': ts['freq'][0], 'fmax': ts['freq'][-1],
                        'points': len(ts['freq']), 'info': ts.get('info') or []})
        except TouchstoneError as e:
            out.append({'file': f.name, 'error': str(e)})
    return jsonify({'devices': out})


@app.post('/api/devices/upload')
def api_devices_upload():
    data = request.get_json(force=True)
    fname = _safe_device_name(data.get('name'))
    if not fname:
        return jsonify({'error': 'file name must end in .sNp (e.g. bjt.s3p)'}), 400
    content = data.get('content') or ''
    m = re.search(r'\.s(\d+)p$', fname, re.I)
    try:
        ts = parse_touchstone(content, int(m.group(1)))
    except TouchstoneError as e:
        return jsonify({'error': f'invalid touchstone file: {e}'}), 400
    (DEV_ROOT / fname).write_text(content)
    return jsonify({'file': fname, 'nports': ts['nports'], 'r': ts['r'],
                    'fmin': ts['freq'][0], 'fmax': ts['freq'][-1]})


@app.get('/api/devices/<name>/data')
def api_devices_data(name):
    """Touchstone preview data: |S_ij| in dB plus re/im (so the GUI can
    draw the reflection coefficients on a Smith chart for comparison
    against datasheet figures)."""
    fname = _safe_device_name(name)
    if not fname or not (DEV_ROOT / fname).is_file():
        return jsonify({'error': 'no such device file'}), 404
    m = re.search(r'\.s(\d+)p$', fname, re.I)
    try:
        ts = parse_touchstone((DEV_ROOT / fname).read_text(), int(m.group(1)))
    except TouchstoneError as e:
        return jsonify({'error': str(e)}), 400
    n = ts['nports']
    series = []
    for i in range(n):
        for j in range(n):
            series.append({
                'label': f'S{i + 1}{j + 1}',
                'values': [round(20 * math.log10(max(abs(mat[i][j]), 1e-12)), 3)
                           for mat in ts['s']],
                're': [round(mat[i][j].real, 6) for mat in ts['s']],
                'im': [round(mat[i][j].imag, 6) for mat in ts['s']],
            })
    return jsonify({'file': fname, 'nports': n, 'r': ts['r'],
                    'freq': ts['freq'], 'series': series,
                    'info': ts.get('info') or []})


@app.delete('/api/devices/<name>')
def api_devices_delete(name):
    fname = _safe_device_name(name)
    if not fname or not (DEV_ROOT / fname).is_file():
        return jsonify({'error': 'no such device file'}), 404
    (DEV_ROOT / fname).unlink()
    return jsonify({'deleted': fname})


@app.get('/api/results/<run_id>/file/<name>')
def api_results_file(run_id, name):
    d = _run_dir(run_id)
    if d is None or not re.fullmatch(
            r'(board_full|combined)\.s\d+p|sparams(_board|_primary)?\.csv', name):
        return jsonify({'error': 'no such file'}), 404
    if not (d / name).is_file():
        return jsonify({'error': 'no such file'}), 404
    return send_from_directory(d, name, mimetype='text/plain')


@app.post('/api/export/gerber')
def api_export_gerber():
    """Zip of RS-274X layers + board outline + Excellon drill file."""
    import io
    import zipfile
    from gerber import export_fabrication
    model = request.get_json(force=True)
    try:
        files = export_fabrication(model)
    except Exception as e:
        return jsonify({'error': f'gerber export failed: {e}'}), 400
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as z:
        for fn, content in files.items():
            z.writestr(fn, content)
    buf.seek(0)
    name = _safe_project_name(model.get('name')) or 'board'
    return send_file(buf, mimetype='application/zip', as_attachment=True,
                     download_name=f'{name}_gerber.zip')


@app.get('/api/runs')
def api_runs():
    """Every simulation run on disk, newest first — the recovery path for
    results whose browser session is long gone."""
    out = []
    for d in sorted(SIM_ROOT.glob('run_*'), reverse=True):
        if not d.is_dir():
            continue
        entry = {
            'runId': d.name,
            'mtime': d.stat().st_mtime,
            'hasResults': (d / 'sparams.csv').is_file(),
            'stages': 1 + sum(1 for _ in d.glob('exc_*/sparams.csv')),
            'project': None,
        }
        pj = d / 'project.json'
        if pj.is_file():
            try:
                entry['project'] = json.loads(pj.read_text()).get('name') or ''
            except (OSError, ValueError):
                pass
        out.append(entry)
        if len(out) >= 200:
            break
    return jsonify({'runs': out})


@app.get('/api/runs/<run_id>/project')
def api_run_project(run_id):
    """The exact model that produced a run (written at launch)."""
    d = _run_dir(run_id)
    if d is None or not (d / 'project.json').is_file():
        return jsonify({'error': 'no design stored for this run'}), 404
    return jsonify({'project': json.loads((d / 'project.json').read_text())})


@app.get('/api/results/<run_id>/stage/<int:exc>')
def api_results_stage(run_id, exc):
    """Raw sparams.csv of one excitation run of a multi-excitation sweep.

    The primary excitation's own file is preserved as sparams_board.csv /
    sparams_primary.csv because the root sparams.csv is rewritten with the
    assembled result; the other excitations keep theirs under exc_<n>/."""
    d = _run_dir(run_id)
    if d is None:
        return jsonify({'error': 'no such run'}), 404
    stage = d / f'exc_{exc}' / 'sparams.csv'
    if not stage.is_file():
        for alt in ('sparams_board.csv', 'sparams_primary.csv'):
            if (d / alt).is_file():
                stage = d / alt
                break
    if not stage.is_file():
        return jsonify({'error': 'no such excitation'}), 404
    return send_from_directory(stage.parent, stage.name, mimetype='text/csv')


def _matrix_dataset(path, key, label):
    """Touchstone file -> {key,label,nports,r,freq,entries:{Sij:{re,im}}}."""
    m = re.search(r'\.s(\d+)p$', path.name, re.I)
    ts = parse_touchstone(path.read_text(), int(m.group(1)))
    n = ts['nports']
    entries = {}
    for i in range(n):
        for j in range(n):
            entries[f'S{i + 1}{j + 1}'] = {
                're': [round(mat[i][j].real, 9) for mat in ts['s']],
                'im': [round(mat[i][j].imag, 9) for mat in ts['s']],
            }
    return {'key': key, 'label': label, 'nports': n, 'r': ts['r'],
            'freq': ts['freq'], 'entries': entries}


@app.get('/api/results/<run_id>/smatrix')
def api_results_smatrix(run_id):
    """Full S-matrices of a multi-excitation run, for the raw-data viewer:
    the assembled board matrix (every excitation, before any device is
    folded in) and, when devices were folded, the resulting network."""
    d = _run_dir(run_id)
    if d is None:
        return jsonify({'error': 'no such run'}), 404
    datasets = []
    board = sorted(d.glob('board_full.s*p'))
    combined = sorted(d.glob('combined.s*p'))
    try:
        for p in board:
            datasets.append(_matrix_dataset(
                p, 'board', f'Raw board matrix — {p.name}'))
        for p in combined:
            # identical to the board matrix when no device was folded in
            if board and p.stat().st_size == board[0].stat().st_size:
                continue
            datasets.append(_matrix_dataset(
                p, 'combined', f'Devices folded in — {p.name}'))
    except TouchstoneError as e:
        return jsonify({'error': f'unreadable matrix file: {e}'}), 400
    stages = sorted(int(p.parent.name[4:]) for p in d.glob('exc_*/sparams.csv'))
    return jsonify({'datasets': datasets, 'stages': stages})


@app.get('/api/tests')
def api_tests_list():
    sys.path.insert(0, str(BASE_DIR / 'tests'))
    try:
        from cases import CASES
    except Exception as e:
        return jsonify({'error': f'cannot load test cases: {e}'}), 500
    return jsonify({'cases': [
        {'id': cid, 'title': c['title'], 'desc': c['desc'], 'minutes': c['minutes']}
        for cid, c in CASES.items()]})


@app.post('/api/tests/run')
def api_tests_run():
    data = request.get_json(force=True)
    try:
        test_runner.start(bool(data.get('unit')), list(data.get('cases') or []))
    except RuntimeError as e:
        return jsonify({'error': str(e)}), 409
    return jsonify({'started': True})


@app.get('/api/tests/status')
def api_tests_status():
    return jsonify(test_runner.status())


# ---------------------------------------------------------------------------
# Project folders: a purely organizational overlay over the flat
# projects/<name>/ storage. Folders nest arbitrarily deep via parent
# pointers, carry optional tags, and live in projects/folders.json —
# moving or renaming a folder never touches result ids or run data.
# ---------------------------------------------------------------------------
FOLDERS_FILE = PROJ_ROOT / 'folders.json'


def _load_folders():
    try:
        d = json.loads(FOLDERS_FILE.read_text())
    except (OSError, ValueError):
        d = {}
    d.setdefault('folders', [])
    d.setdefault('assign', {})
    return d


def _save_folders(d):
    PROJ_ROOT.mkdir(parents=True, exist_ok=True)
    FOLDERS_FILE.write_text(json.dumps(d, indent=1))


def _folder_by_id(d, fid):
    return next((f for f in d['folders'] if f['id'] == fid), None)


def _is_descendant(d, fid, maybe_ancestor):
    """True if `fid` is (or descends from) `maybe_ancestor`."""
    seen = set()
    while fid is not None and fid not in seen:
        if fid == maybe_ancestor:
            return True
        seen.add(fid)
        f = _folder_by_id(d, fid)
        fid = f['parent'] if f else None
    return False


def _clean_tags(tags):
    out = []
    for t in (tags or []):
        t = str(t).strip()[:24]
        if t and t not in out:
            out.append(t)
    return out[:12]


@app.get('/api/folders')
def api_folders():
    d = _load_folders()
    # hygiene: only report assignments whose project still exists
    assign = {p: f for p, f in d['assign'].items()
              if (PROJ_ROOT / p / 'project.json').is_file()
              and _folder_by_id(d, f)}
    return jsonify({'folders': d['folders'], 'assign': assign})


@app.post('/api/folders')
def api_folders_create():
    data = request.get_json(force=True)
    name = str(data.get('name') or '').strip()[:60]
    if not name:
        return jsonify({'error': 'folder name required'}), 400
    d = _load_folders()
    parent = data.get('parent') or None
    if parent is not None and not _folder_by_id(d, parent):
        return jsonify({'error': 'no such parent folder'}), 404
    fid = 'f_' + uuid.uuid4().hex[:8]
    folder = {'id': fid, 'name': name, 'parent': parent,
              'tags': _clean_tags(data.get('tags'))}
    d['folders'].append(folder)
    _save_folders(d)
    return jsonify(folder)


@app.post('/api/folders/<fid>')
def api_folders_update(fid):
    data = request.get_json(force=True)
    d = _load_folders()
    f = _folder_by_id(d, fid)
    if not f:
        return jsonify({'error': 'no such folder'}), 404
    if 'name' in data:
        name = str(data['name'] or '').strip()[:60]
        if not name:
            return jsonify({'error': 'folder name required'}), 400
        f['name'] = name
    if 'tags' in data:
        f['tags'] = _clean_tags(data['tags'])
    if 'parent' in data:
        parent = data['parent'] or None
        if parent is not None:
            if not _folder_by_id(d, parent):
                return jsonify({'error': 'no such parent folder'}), 404
            if _is_descendant(d, parent, fid):
                return jsonify({'error': 'cannot move a folder into itself'}), 400
        f['parent'] = parent
    _save_folders(d)
    return jsonify(f)


@app.delete('/api/folders/<fid>')
def api_folders_delete(fid):
    d = _load_folders()
    f = _folder_by_id(d, fid)
    if not f:
        return jsonify({'error': 'no such folder'}), 404
    # contents survive: children and projects move to the deleted
    # folder's parent (or the root)
    for child in d['folders']:
        if child['parent'] == fid:
            child['parent'] = f['parent']
    for proj, fol in list(d['assign'].items()):
        if fol == fid:
            if f['parent']:
                d['assign'][proj] = f['parent']
            else:
                del d['assign'][proj]
    d['folders'] = [x for x in d['folders'] if x['id'] != fid]
    _save_folders(d)
    return jsonify({'deleted': fid})


@app.post('/api/folders/assign')
def api_folders_assign():
    data = request.get_json(force=True)
    safe = _safe_project_name(data.get('project'))
    if not safe or not (PROJ_ROOT / safe / 'project.json').is_file():
        return jsonify({'error': 'no such project'}), 404
    d = _load_folders()
    fid = data.get('folder') or None
    if fid is None:
        d['assign'].pop(safe, None)
    else:
        if not _folder_by_id(d, fid):
            return jsonify({'error': 'no such folder'}), 404
        d['assign'][safe] = fid
    _save_folders(d)
    return jsonify({'project': safe, 'folder': fid})


@app.get('/api/projects')
def api_projects_list():
    out = []
    for d in sorted(PROJ_ROOT.iterdir()):
        pj = d / 'project.json'
        if d.is_dir() and pj.is_file():
            runs = _project_runs(d.name)
            out.append({
                'name': d.name,
                'mtime': pj.stat().st_mtime,
                'hasResults': any(r['hasResults'] for r in runs),
                'runCount': len(runs),
            })
    out.sort(key=lambda p: -p['mtime'])
    return jsonify({'projects': out})


def _copy_results(src, dst):
    """Copy a run's result files to dst (replacing it), excluding the
    bulky raw field dumps. Each excitation's exc_<n>/ subdirectory keeps
    its sparams.csv (raw-data links) plus the processed current-density
    exports (jdumps/jtdumps listings and .bin frames), so the J viewer
    works for every excitation of a stored run."""
    if dst.is_dir():
        shutil.rmtree(dst)
    dst.mkdir(parents=True)
    for f in src.iterdir():
        if f.is_dir():
            if f.name.startswith('exc_') and (f / 'sparams.csv').is_file():
                (dst / f.name).mkdir()
                for g in f.iterdir():
                    if not g.is_file():
                        continue
                    if (g.name == 'sparams.csv' or g.suffix == '.bin'
                            or g.name in ('jdumps.csv', 'jtdumps.csv')
                            or g.name.startswith(('port_ut', 'port_it'))):
                        shutil.copy2(g, dst / f.name / g.name)
            continue
        # skip bulky raw field dumps - the GUI uses the .bin exports
        if f.suffix in ('.h5', '.vtr'):
            continue
        shutil.copy2(f, dst / f.name)


@app.post('/api/projects/save')
def api_projects_save():
    data = request.get_json(force=True)
    safe = _safe_project_name(data.get('name'))
    if not safe:
        return jsonify({'error': 'invalid project name'}), 400
    project = data.get('project')
    if not isinstance(project, dict):
        return jsonify({'error': 'missing project data'}), 400
    pdir = PROJ_ROOT / safe
    pdir.mkdir(parents=True, exist_ok=True)
    (pdir / 'project.json').write_text(json.dumps(project, indent=1))
    copied = False
    run_id = data.get('runId')
    if run_id and re.fullmatch(r'run_[0-9_]+', str(run_id)):
        src = SIM_ROOT / run_id
        if src.is_dir() and (src / 'sparams.csv').is_file():
            _copy_results(src, pdir / 'runs' / run_id)
            copied = True
    return jsonify({'name': safe, 'resultsSaved': copied})


@app.get('/api/projects/<name>')
def api_projects_get(name):
    safe = _safe_project_name(name)
    pdir = PROJ_ROOT / (safe or '')
    if not safe or not (pdir / 'project.json').is_file():
        return jsonify({'error': 'no such project'}), 404
    project = json.loads((pdir / 'project.json').read_text())
    runs = _project_runs(safe)
    newest = next((r for r in runs if r['hasResults']), None)
    return jsonify({'project': project,
                    'resultsId': newest['resultsId'] if newest else None,
                    'runCount': len(runs)})


@app.delete('/api/projects/<name>')
def api_projects_delete(name):
    safe = _safe_project_name(name)
    pdir = PROJ_ROOT / (safe or '')
    if not safe or not (pdir / 'project.json').is_file():
        return jsonify({'error': 'no such project'}), 404
    shutil.rmtree(pdir)
    return jsonify({'deleted': safe})


@app.get('/api/projects/<name>/runs')
def api_project_runs(name):
    safe = _safe_project_name(name)
    if not safe or not (PROJ_ROOT / safe / 'project.json').is_file():
        return jsonify({'error': 'no such project'}), 404
    return jsonify({'runs': _project_runs(safe)})


@app.get('/api/projects/<name>/runs/<run_id>/project')
def api_project_run_design(name, run_id):
    """The editor state stored with one of the project's runs."""
    safe = _safe_project_name(name)
    if not safe or not re.fullmatch(r'run_[0-9_]+', run_id):
        return jsonify({'error': 'no such run'}), 404
    pj = PROJ_ROOT / safe / 'runs' / run_id / 'project.json'
    if not pj.is_file():
        return jsonify({'error': 'no design stored with this run'}), 404
    return jsonify({'project': json.loads(pj.read_text())})


@app.delete('/api/projects/<name>/runs/<run_id>')
def api_project_run_delete(name, run_id):
    safe = _safe_project_name(name)
    if not safe or not re.fullmatch(r'run_[0-9_]+', run_id):
        return jsonify({'error': 'no such run'}), 404
    d = PROJ_ROOT / safe / 'runs' / run_id
    if not d.is_dir():
        return jsonify({'error': 'no such stored run'}), 404
    shutil.rmtree(d)
    return jsonify({'deleted': run_id})


@app.get('/api/tools')
def api_tools():
    """Registered advanced tools, for the Tools menu. Adding a tool is a
    module drop-in - nothing here changes."""
    try:
        import advtools
        return jsonify({'tools': advtools.list_tools()})
    except Exception as e:
        return jsonify({'tools': [], 'error': str(e)})


@app.post('/api/tools/<tool_id>/<action>')
def api_tool_action(tool_id, action):
    """Run one action of one advanced tool."""
    import advtools
    payload = request.get_json(silent=True) or {}
    try:
        return jsonify(advtools.dispatch(tool_id, action, payload))
    except KeyError as e:
        return jsonify({'error': str(e)}), 404
    except (ValueError, TypeError) as e:
        return jsonify({'error': str(e)}), 400
    except Exception as e:
        app.logger.exception('tool %s/%s failed', tool_id, action)
        return jsonify({'error': f'{type(e).__name__}: {e}'}), 500


@app.post('/api/simplify')
def api_simplify():
    """Simplify a model's shapes: merge imported stroke chains into
    centerline traces, decimate curve tessellations, resample curves.
    Body: {model, opts:{ids?, traces?, polys?, tol?, maxSeg?}}. Returns
    the full replacement shape list, stats and before/after mesh sizes."""
    from simplify import simplify_shapes
    data = request.get_json(force=True) or {}
    model = data.get('model') or {}
    try:
        shapes, stats = simplify_shapes(model.get('shapes') or [], data.get('opts') or {})
    except (ValueError, TypeError, KeyError) as e:
        return jsonify({'error': str(e)}), 400
    out = {'shapes': shapes, 'stats': stats}
    try:
        for key, mm in (('meshBefore', model),
                        ('meshAfter', {**model, 'shapes': shapes})):
            mesh = build_mesh(mm)
            out[key] = {'cells': mesh['cells'], 'minCell': mesh['minCell'],
                        'worstRatio': mesh['worstRatio'],
                        'nx': len(mesh['x']), 'ny': len(mesh['y']), 'nz': len(mesh['z'])}
    except Exception:
        pass   # mesh preview is best-effort; the shape list is the result
    return jsonify(out)


@app.post('/api/import/gerber')
def api_import_gerber():
    data = request.get_json(force=True)
    try:
        return jsonify(parse_gerber(data.get('content') or ''))
    except GerberError as e:
        return jsonify({'error': str(e)}), 400


@app.post('/api/import/drill')
def api_import_drill():
    data = request.get_json(force=True)
    try:
        return jsonify(parse_excellon(data.get('content') or ''))
    except GerberError as e:
        return jsonify({'error': str(e)}), 400


@app.get('/api/results/<run_id>/jtdumps')
def api_jtdumps(run_id):
    d = _dump_dir(run_id)
    if d is None or not (d / 'jtdumps.csv').is_file():
        return jsonify({'dumps': []})
    dumps = []
    for line in (d / 'jtdumps.csv').read_text().strip().splitlines():
        parts = line.split(',')
        if len(parts) == 2 and (d / f'J_td_{re.sub(r"[^A-Za-z0-9]", "_", parts[0])}.bin').is_file():
            dumps.append({'layer': parts[0], 'frames': int(parts[1])})
    return jsonify({'dumps': dumps})


@app.get('/api/results/<run_id>/jtdump/<layer>')
def api_jtdump(run_id, layer):
    d = _dump_dir(run_id)
    fname = f'J_td_{re.sub(r"[^A-Za-z0-9]", "_", layer)}.bin'
    if d is None or not (d / fname).is_file():
        return jsonify({'error': 'no such dump'}), 404
    return send_from_directory(d, fname, mimetype='application/octet-stream')


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8036))
    print(f'OpenEMS PCB Studio: http://localhost:{port}')
    app.run(host='127.0.0.1', port=port, threaded=True)
